gitRepoId: dotposthog
gitUserId: kamranayub
modelNamePrefix: PostHog
inputSpec: schema.yaml
nameMappings:
  $distinct_id: "SysDistinctId"
  $token: "SysToken"
  $set: "SysSet"
  $set_once: "SysSetOnce"
parameterNameMapping:
  $distinct_id: "sysDistinctId"
  $token: "sysToken"
  $set: "sysSet"
  $set_once: "sysSetOnce"
additionalProperties:
  library: "restsharp"
  licenseId: "Apache-2.0"
  packageName: "DotPostHog"
  packageTags: "posthog dotnet feature-flags events analytics"
  sourceFolder: "src"
  targetFramework: "netstandard2.0"
