additionalProperties:
  apiName: "PostHogApi"
  library: "restsharp"
  licenseId: "Apache-2.0"
  packageName: "DotPostHog"
  packageTags: "posthog dotnet feature-flags events analytics"
  sourceFolder: "src"
  targetFramework: "netstandard2.0"
modelNameMappings:
  Action: "PostHogAction"