/*
 * PostHog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DotPostHog.Model;
using DotPostHog.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DotPostHog.Test.Model
{
    /// <summary>
    ///  Class for testing DashboardTileBasic
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DashboardTileBasicTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DashboardTileBasic
        //private DashboardTileBasic instance;

        public DashboardTileBasicTests()
        {
            // TODO uncomment below to create an instance of DashboardTileBasic
            //instance = new DashboardTileBasic();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DashboardTileBasic
        /// </summary>
        [Fact]
        public void DashboardTileBasicInstanceTest()
        {
            // TODO uncomment below to test "IsType" DashboardTileBasic
            //Assert.IsType<DashboardTileBasic>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'DashboardId'
        /// </summary>
        [Fact]
        public void DashboardIdTest()
        {
            // TODO unit test for the property 'DashboardId'
        }

        /// <summary>
        /// Test the property 'Deleted'
        /// </summary>
        [Fact]
        public void DeletedTest()
        {
            // TODO unit test for the property 'Deleted'
        }
    }
}
