/*
 * PostHog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DotPostHog.Model;
using DotPostHog.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DotPostHog.Test.Model
{
    /// <summary>
    ///  Class for testing GenericInsights
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GenericInsightsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GenericInsights
        //private GenericInsights instance;

        public GenericInsightsTests()
        {
            // TODO uncomment below to create an instance of GenericInsights
            //instance = new GenericInsights();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GenericInsights
        /// </summary>
        [Fact]
        public void GenericInsightsInstanceTest()
        {
            // TODO uncomment below to test "IsType" GenericInsights
            //Assert.IsType<GenericInsights>(instance);
        }

        /// <summary>
        /// Test the property 'Events'
        /// </summary>
        [Fact]
        public void EventsTest()
        {
            // TODO unit test for the property 'Events'
        }

        /// <summary>
        /// Test the property 'Actions'
        /// </summary>
        [Fact]
        public void ActionsTest()
        {
            // TODO unit test for the property 'Actions'
        }

        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Fact]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }

        /// <summary>
        /// Test the property 'FilterTestAccounts'
        /// </summary>
        [Fact]
        public void FilterTestAccountsTest()
        {
            // TODO unit test for the property 'FilterTestAccounts'
        }

        /// <summary>
        /// Test the property 'DateFrom'
        /// </summary>
        [Fact]
        public void DateFromTest()
        {
            // TODO unit test for the property 'DateFrom'
        }

        /// <summary>
        /// Test the property 'DateTo'
        /// </summary>
        [Fact]
        public void DateToTest()
        {
            // TODO unit test for the property 'DateTo'
        }
    }
}
