/*
 * PostHog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DotPostHog.Model;
using DotPostHog.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DotPostHog.Test.Model
{
    /// <summary>
    ///  Class for testing PostHogEventsCaptureRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostHogEventsCaptureRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostHogEventsCaptureRequest
        //private PostHogEventsCaptureRequest instance;

        public PostHogEventsCaptureRequestTests()
        {
            // TODO uncomment below to create an instance of PostHogEventsCaptureRequest
            //instance = new PostHogEventsCaptureRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostHogEventsCaptureRequest
        /// </summary>
        [Fact]
        public void PostHogEventsCaptureRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostHogEventsCaptureRequest
            //Assert.IsType<PostHogEventsCaptureRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ApiKey'
        /// </summary>
        [Fact]
        public void ApiKeyTest()
        {
            // TODO unit test for the property 'ApiKey'
        }

        /// <summary>
        /// Test the property 'Batch'
        /// </summary>
        [Fact]
        public void BatchTest()
        {
            // TODO unit test for the property 'Batch'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
