/*
 * PostHog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DotPostHog.Model;
using DotPostHog.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DotPostHog.Test.Model
{
    /// <summary>
    ///  Class for testing PostHogPatchedCohort
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostHogPatchedCohortTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostHogPatchedCohort
        //private PostHogPatchedCohort instance;

        public PostHogPatchedCohortTests()
        {
            // TODO uncomment below to create an instance of PostHogPatchedCohort
            //instance = new PostHogPatchedCohort();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostHogPatchedCohort
        /// </summary>
        [Fact]
        public void PostHogPatchedCohortInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostHogPatchedCohort
            //Assert.IsType<PostHogPatchedCohort>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Groups'
        /// </summary>
        [Fact]
        public void GroupsTest()
        {
            // TODO unit test for the property 'Groups'
        }

        /// <summary>
        /// Test the property 'Deleted'
        /// </summary>
        [Fact]
        public void DeletedTest()
        {
            // TODO unit test for the property 'Deleted'
        }

        /// <summary>
        /// Test the property 'Filters'
        /// </summary>
        [Fact]
        public void FiltersTest()
        {
            // TODO unit test for the property 'Filters'
        }

        /// <summary>
        /// Test the property 'IsCalculating'
        /// </summary>
        [Fact]
        public void IsCalculatingTest()
        {
            // TODO unit test for the property 'IsCalculating'
        }

        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Fact]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'LastCalculation'
        /// </summary>
        [Fact]
        public void LastCalculationTest()
        {
            // TODO unit test for the property 'LastCalculation'
        }

        /// <summary>
        /// Test the property 'ErrorsCalculating'
        /// </summary>
        [Fact]
        public void ErrorsCalculatingTest()
        {
            // TODO unit test for the property 'ErrorsCalculating'
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }

        /// <summary>
        /// Test the property 'IsStatic'
        /// </summary>
        [Fact]
        public void IsStaticTest()
        {
            // TODO unit test for the property 'IsStatic'
        }
    }
}
