/*
 * PostHog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DotPostHog.Model;
using DotPostHog.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DotPostHog.Test.Model
{
    /// <summary>
    ///  Class for testing PostHogPropertyItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostHogPropertyItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostHogPropertyItem
        //private PostHogPropertyItem instance;

        public PostHogPropertyItemTests()
        {
            // TODO uncomment below to create an instance of PostHogPropertyItem
            //instance = new PostHogPropertyItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostHogPropertyItem
        /// </summary>
        [Fact]
        public void PostHogPropertyItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostHogPropertyItem
            //Assert.IsType<PostHogPropertyItem>(instance);
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'VarOperator'
        /// </summary>
        [Fact]
        public void VarOperatorTest()
        {
            // TODO unit test for the property 'VarOperator'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
