/*
 * PostHog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DotPostHog.Model;
using DotPostHog.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DotPostHog.Test.Model
{
    /// <summary>
    ///  Class for testing Trend
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TrendTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Trend
        //private Trend instance;

        public TrendTests()
        {
            // TODO uncomment below to create an instance of Trend
            //instance = new Trend();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Trend
        /// </summary>
        [Fact]
        public void TrendInstanceTest()
        {
            // TODO uncomment below to test "IsType" Trend
            //Assert.IsType<Trend>(instance);
        }

        /// <summary>
        /// Test the property 'Events'
        /// </summary>
        [Fact]
        public void EventsTest()
        {
            // TODO unit test for the property 'Events'
        }

        /// <summary>
        /// Test the property 'Actions'
        /// </summary>
        [Fact]
        public void ActionsTest()
        {
            // TODO unit test for the property 'Actions'
        }

        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Fact]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }

        /// <summary>
        /// Test the property 'FilterTestAccounts'
        /// </summary>
        [Fact]
        public void FilterTestAccountsTest()
        {
            // TODO unit test for the property 'FilterTestAccounts'
        }

        /// <summary>
        /// Test the property 'DateFrom'
        /// </summary>
        [Fact]
        public void DateFromTest()
        {
            // TODO unit test for the property 'DateFrom'
        }

        /// <summary>
        /// Test the property 'DateTo'
        /// </summary>
        [Fact]
        public void DateToTest()
        {
            // TODO unit test for the property 'DateTo'
        }

        /// <summary>
        /// Test the property 'Breakdown'
        /// </summary>
        [Fact]
        public void BreakdownTest()
        {
            // TODO unit test for the property 'Breakdown'
        }

        /// <summary>
        /// Test the property 'BreakdownType'
        /// </summary>
        [Fact]
        public void BreakdownTypeTest()
        {
            // TODO unit test for the property 'BreakdownType'
        }

        /// <summary>
        /// Test the property 'Display'
        /// </summary>
        [Fact]
        public void DisplayTest()
        {
            // TODO unit test for the property 'Display'
        }

        /// <summary>
        /// Test the property 'Formula'
        /// </summary>
        [Fact]
        public void FormulaTest()
        {
            // TODO unit test for the property 'Formula'
        }

        /// <summary>
        /// Test the property 'Compare'
        /// </summary>
        [Fact]
        public void CompareTest()
        {
            // TODO unit test for the property 'Compare'
        }
    }
}
