on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-preview[0-9]"
      - "[0-9]+.[0-9]+.[0-9]+-preview[0-9][0-9]"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Pack
        run: dotnet pack -c Release src/DotPostHog/DotPostHog.csproj /p:Version=${VERSION} --output .
      - name: Push
        run: dotnet nuget push DotPostHog.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
