/*
 * PostHog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using DotPostHog.Client;
using DotPostHog.Api;
// uncomment below to import models
//using DotPostHog.Model;

namespace DotPostHog.Test.Api
{
    /// <summary>
    ///  Class for testing WarehouseViewLinksApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class WarehouseViewLinksApiTests : IDisposable
    {
        private WarehouseViewLinksApi instance;

        public WarehouseViewLinksApiTests()
        {
            instance = new WarehouseViewLinksApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WarehouseViewLinksApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' WarehouseViewLinksApi
            //Assert.IsType<WarehouseViewLinksApi>(instance);
        }

        /// <summary>
        /// Test WarehouseViewLinksCreate
        /// </summary>
        [Fact]
        public void WarehouseViewLinksCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectId = null;
            //PostHogViewLink postHogViewLink = null;
            //var response = instance.WarehouseViewLinksCreate(projectId, postHogViewLink);
            //Assert.IsType<PostHogViewLink>(response);
        }

        /// <summary>
        /// Test WarehouseViewLinksDestroy
        /// </summary>
        [Fact]
        public void WarehouseViewLinksDestroyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //string projectId = null;
            //instance.WarehouseViewLinksDestroy(id, projectId);
        }

        /// <summary>
        /// Test WarehouseViewLinksList
        /// </summary>
        [Fact]
        public void WarehouseViewLinksListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectId = null;
            //int? limit = null;
            //int? offset = null;
            //string search = null;
            //var response = instance.WarehouseViewLinksList(projectId, limit, offset, search);
            //Assert.IsType<PostHogPaginatedViewLinkList>(response);
        }

        /// <summary>
        /// Test WarehouseViewLinksPartialUpdate
        /// </summary>
        [Fact]
        public void WarehouseViewLinksPartialUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //string projectId = null;
            //PostHogPatchedViewLink postHogPatchedViewLink = null;
            //var response = instance.WarehouseViewLinksPartialUpdate(id, projectId, postHogPatchedViewLink);
            //Assert.IsType<PostHogViewLink>(response);
        }

        /// <summary>
        /// Test WarehouseViewLinksRetrieve
        /// </summary>
        [Fact]
        public void WarehouseViewLinksRetrieveTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //string projectId = null;
            //var response = instance.WarehouseViewLinksRetrieve(id, projectId);
            //Assert.IsType<PostHogViewLink>(response);
        }

        /// <summary>
        /// Test WarehouseViewLinksUpdate
        /// </summary>
        [Fact]
        public void WarehouseViewLinksUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //string projectId = null;
            //PostHogViewLink postHogViewLink = null;
            //var response = instance.WarehouseViewLinksUpdate(id, projectId, postHogViewLink);
            //Assert.IsType<PostHogViewLink>(response);
        }
    }
}
