/*
 * PostHog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using DotPostHog.Client;
using DotPostHog.Api;
// uncomment below to import models
//using DotPostHog.Model;

namespace DotPostHog.Test.Api
{
    /// <summary>
    ///  Class for testing WarehouseSavedQueriesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class WarehouseSavedQueriesApiTests : IDisposable
    {
        private WarehouseSavedQueriesApi instance;

        public WarehouseSavedQueriesApiTests()
        {
            instance = new WarehouseSavedQueriesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WarehouseSavedQueriesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' WarehouseSavedQueriesApi
            //Assert.IsType<WarehouseSavedQueriesApi>(instance);
        }

        /// <summary>
        /// Test WarehouseSavedQueriesCreate
        /// </summary>
        [Fact]
        public void WarehouseSavedQueriesCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectId = null;
            //DataWarehouseSavedQuery dataWarehouseSavedQuery = null;
            //var response = instance.WarehouseSavedQueriesCreate(projectId, dataWarehouseSavedQuery);
            //Assert.IsType<DataWarehouseSavedQuery>(response);
        }

        /// <summary>
        /// Test WarehouseSavedQueriesDestroy
        /// </summary>
        [Fact]
        public void WarehouseSavedQueriesDestroyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //string projectId = null;
            //instance.WarehouseSavedQueriesDestroy(id, projectId);
        }

        /// <summary>
        /// Test WarehouseSavedQueriesList
        /// </summary>
        [Fact]
        public void WarehouseSavedQueriesListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectId = null;
            //int? limit = null;
            //int? offset = null;
            //string search = null;
            //var response = instance.WarehouseSavedQueriesList(projectId, limit, offset, search);
            //Assert.IsType<PaginatedDataWarehouseSavedQueryList>(response);
        }

        /// <summary>
        /// Test WarehouseSavedQueriesPartialUpdate
        /// </summary>
        [Fact]
        public void WarehouseSavedQueriesPartialUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //string projectId = null;
            //PatchedDataWarehouseSavedQuery patchedDataWarehouseSavedQuery = null;
            //var response = instance.WarehouseSavedQueriesPartialUpdate(id, projectId, patchedDataWarehouseSavedQuery);
            //Assert.IsType<DataWarehouseSavedQuery>(response);
        }

        /// <summary>
        /// Test WarehouseSavedQueriesRetrieve
        /// </summary>
        [Fact]
        public void WarehouseSavedQueriesRetrieveTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //string projectId = null;
            //var response = instance.WarehouseSavedQueriesRetrieve(id, projectId);
            //Assert.IsType<DataWarehouseSavedQuery>(response);
        }

        /// <summary>
        /// Test WarehouseSavedQueriesUpdate
        /// </summary>
        [Fact]
        public void WarehouseSavedQueriesUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //string projectId = null;
            //DataWarehouseSavedQuery dataWarehouseSavedQuery = null;
            //var response = instance.WarehouseSavedQueriesUpdate(id, projectId, dataWarehouseSavedQuery);
            //Assert.IsType<DataWarehouseSavedQuery>(response);
        }
    }
}
